name: 'Terraform CI/CD'

on:
  push:
    branches:
      - master
      - dev
      - stage
      - prod

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1

      - name: 'Terraform Init'
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: 'Terraform Format and Commit Changes'
        run: |
          terraform fmt -recursive
          git add .
          if [[ `git status --porcelain` ]]; then
            git config --local user.name "jenserling"
            git config --local user.email "jensebra@stud.ntnu.no"
            git commit -m "Format Terraform files"
            # Use the PAT stored in the secrets to push the changes
            git push https://${{ secrets.GIT_PAT }}@github.com/jenserling/iac-oppgave2.git
            
          else
            echo "No changes to commit"
          fi
        env:
          TERRAFORM_CLI_PATH: ${{ env.TERRAFORM_CLI_PATH }}

      - name: 'Terraform Plan'
        run: terraform plan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
